http-5204-a-n01330654-passion-project/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Data.SqlClient;
using System.Data.Entity;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;
using http_5204_a_n01330654_passion_project.Models;
using http_5204_a_n01330654_passion_project.Models.ViewModels;

namespace http_5204_a_n01330654_passion_project.Controllers
{
    public class GalleryController : Controller
    {
        private PixelSnapCMS db = new PixelSnapCMS();

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            IEnumerable<Gallery> galleries = db.Galleries.ToList();
            return View(galleries);
        }
        public ActionResult New()
        {
            GalleryEdit galleryeditview = new GalleryEdit();

            return View(galleryeditview);
        }
        [HttpPost]
        public ActionResult New(string GalleryName_New, string GalleryDescription_New)
        {
            string query = "insert into Galleries (GalleryName, GalleryDescription) values (@name, @description)";

            SqlParameter[] myparams = new SqlParameter[2];
            myparams[0] = new SqlParameter("@name", GalleryName_New);
            myparams[1] = new SqlParameter("@description", GalleryDescription_New);

            db.Database.ExecuteSqlCommand(query, myparams);
            return RedirectToAction("List");

        }public ActionResult Edit(int id)
        {
            GalleryEdit galleryeditview = new GalleryEdit();
            galleryeditview.gallery = db.Galleries.Find(id);
            return View(galleryeditview);
        }

        [HttpPost]
        public ActionResult Edit(int id, string GalleryName_New, string GalleryDescription_New)
        {
            if((id == null) || (db.Galleries.Find(id) == null))
            {
                return HttpNotFound();
            }
            string query = "update Galleries set GalleryName=@name, GalleryDescription=@description where GalleryID=@id";

            SqlParameter[] myparams = new SqlParameter[3];
            myparams[0] = new SqlParameter("@name", GalleryName_New);
            myparams[1] = new SqlParameter("@description", GalleryDescription_New);
            myparams[2] = new SqlParameter("@id", id);

            db.Database.ExecuteSqlCommand(query, myparams);
            return RedirectToAction("Show/"+id);

        }
        public ActionResult Show(int? id)
        {
    
            if ((id == null) || (db.Galleries.Find(id) == null))
            {
                return HttpNotFound();

            }
            string query = "select * from Galleries where GalleryID=@id";
           
            SqlParameter[] myparams = new SqlParameter[1];
            myparams[0] = new SqlParameter("@id", id);

            Gallery mygallery = db.Galleries.SqlQuery(query, myparams).FirstOrDefault();

            return View(mygallery);
        }

        public ActionResult Delete(int id)
        {
            string query = "delete from Galleries where GalleryID = @id";
            db.Database.ExecuteSqlCommand(query, new SqlParameter("@id", id));
            return RedirectToAction("List");
        }
    }
}

http-5204-a-n01330654-passion-project/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;
using System.IO;
using http_5204_a_n01330654_passion_project.Models;
using http_5204_a_n01330654_passion_project.Models.ViewModels;

namespace http_5204_a_n01330654_passion_project.Controllers
{
    public class ImageController : Controller
    {
        private PixelSnapCMS db = new PixelSnapCMS();

        // GET: Image
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }



        //public ActionResult Create()
        //{
        //    return View(db.Galleries.ToList());
        //}

        //public ActionResult Create(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Image image = db.Images.Find(id);
        //    if (image == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(image);
        //}


        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "ImageID,ImageName,ImageDescription")] Image image, HttpPostedFileBase shareImage)
        //{
  
        //    image.HasPic = 0;


        //    if (shareImage.ContentLength > 0)
        //    {
               
        //        var valtypes = new[] { "jpeg", "jpg", "png", "gif" };
        //        var extension = Path.GetExtension(shareImage.FileName).Substring(1);

        //        if (valtypes.Contains(extension))
        //        {

        //            string fn = image.ImageID + "." + extension;

        //            string path = Path.Combine(Server.MapPath("~/Images/Landscape"), fn);

        //            shareImage.SaveAs(path);

        //            image.HasPic = 1;
        //            image.ImgType = extension;

        //        }
        //    }
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(image).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("List");
        //    }
        //    return View(image);
        //}
    }
}

http-5204-a-n01330654-passion-project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PixelSnap", "Index", "Page", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Page")</li>
                    <li>@Html.ActionLink("Galleries", "Index", "Gallery")</li>
                    <li>@Html.ActionLink("Share Images", "Index", "Image")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Pixel Snap | Developed and Designed by Enrina Wilms | All Rights Reserved.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>